version: "3.0"

services:

  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - "8000:8000"
    command: gunicorn -w 1 --worker-class gthread --bind :8000 app:app


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "5550:5550"
    depends_on:
      - flask_app
